#!/bin/bash
echo "--- Building ---"
./build
pwd=`pwd`
current_dir=`basename $pwd`
tar -cf /tmp/netty-chat.tar "../"$current_dir

echo "--- Copy and untar to agnes ---"
scp /tmp/netty-chat.tar agnes:/tmp
ssh agnes "cd /tmp; tar -xf netty-chat.tar"

echo "--- Copy and untar chalmers ---"
scp /tmp/netty-chat.tar chalmers:/tmp
ssh chalmers "cd /tmp; tar -xf netty-chat.tar"

echo "--- Copy and untar kevin ---"
scp /tmp/netty-chat.tar kevin:/tmp
ssh kevin "cd /tmp; tar -xf netty-chat.tar"
